/**
 * AiNoma Verified AI Tools Directory Database
 * 18 Localized, Tested, and Benchmarked AI Tools for Uzbekistan
 */
window.AINOMA_TOOLS = {
  gamma: {
    id: "gamma",
    name: "Gamma AI",
    kicker: "AI vosita · Prezentatsiya & Hujjatlar",
    headline: "Taqdimotga slayd kerak, lekin PowerPoint'da dizayn tuzishga soatlab vaqtingiz ketyaptimi? <b>Gamma AI</b> bitta mavzu orqali bir necha daqiqada tayyor, chiroyli va interaktiv prezentatsiya tayyorlaydi.",
    category: "Prezentatsiya & Slayd",
    pricing: "Freemium (Bepul kreditlar)",
    lang: "To‘liq qo‘llab-quvvatlanadi",
    url: "https://try.gamma.app/phx9znt88tpu",
    bg: "#7c3aed",
    initial: "G",
    f1_t: "1 ta promptdan to‘liq slaydlar",
    f1_d: "Mavzuni kiritishingiz bilan barcha slaydlarni mantiqiy tartib, sarlavha va rasmlar bilan tuzadi.",
    f2_t: "Moslashuvchan dizayn",
    f2_d: "Matn o‘zgarsa ham slayd buzilmaydi, telefon va kompyuterga avtomatik moslashadi.",
    f3_t: "Veb va hujjat formati",
    f3_d: "Faqat slayd emas, balki bir bosishda chiroyli hujjat yoki veb-sahifa shaklida yuklaysiz.",
    benefit: "Dizayner yollamasdan, professional taqdimot va taklifnomalarni o‘zingiz bir necha daqiqada chiqarasiz.",
    prompt: "O‘zbekistondagi B2B kompaniyalar uchun sun’iy intellekt asosidagi avtomatlashtirish xizmatlari haqida 8 slayddan iborat tijorat taqdimoti tayyorla. Auditoriya: biznes egalari va direktorlar. Ranglar: toza oq va zumrad yashil."
  },
  seamless: {
    id: "seamless",
    name: "Seamless.ai",
    kicker: "AI vosita · B2B Lead Qidiruvi",
    headline: "Xorijiy bozorlarga chiqishda qaror qabul qiluvchi rahbarlar kontaktini topish qiyin bo‘lyaptimi? <b>Seamless.ai</b> real vaqtda tekshirilgan mobil telefonlar va korporativ pochtalarni topib beradi.",
    category: "B2B Lead & Savdo",
    pricing: "Freemium / Yillik obuna",
    lang: "Ingliz (Global B2B qidiruv)",
    url: "https://get.seamless.ai/wxur32uh7xzb",
    bg: "#0284c7",
    initial: "S",
    f1_t: "Real-time kontakt tekshiruvi",
    f1_d: "Eskirgan bazalar emas, sun’iy intellekt orqali ayni paytda faol telefon va email manzillarni aniqlaydi.",
    f2_t: "Chrome Extension",
    f2_d: "LinkedIn orqali profillarni ko‘rayotganda 1 bosishda to‘g‘ridan-to‘g‘ri telefon va emailni ochib beradi.",
    f3_t: "CRM integratsiya",
    f3_d: "Topilgan kontaktlarni HubSpot, Salesforce yoki Excel/CSV formatga darhol eksport qilish imkoniyati.",
    benefit: "Mijoz qidirishga haftalab sarflanadigan vaqtni bir necha daqiqaga tushirib, savdo jamoasini to‘g‘ridan-to‘g‘ri muloqotga yo‘naltiradi.",
    prompt: "Biz O‘zbekistondan turib tekstil mahsulotlarini Yevropa bozoriga eksport qilmoqchimiz. Germaniyadagi kiyim-kechak chakana brendlari xarid bo‘yicha direktorlarining LinkedIn qidiruv filtrlari va muloqot boshlash strategiyasini tuzib ber."
  },
  descript: {
    id: "descript",
    name: "Descript",
    kicker: "AI vosita · Video & Ovoz Montaji",
    headline: "Video montaj qilish uchun murakkab dasturlarda soatlab vaqt yo‘qotyapsizmi? <b>Descript</b> videodagi ovozni matnga aylantiradi — siz esa xuddi matnni o‘chirgandek videoni tahrir qilasiz.",
    category: "Video & Audio Montaj",
    pricing: "Freemium / Pro",
    lang: "Ingliz, Rus (O‘zbek tili transkripsiyada rivojlanmoqda)",
    url: "https://get.descript.com/turigheoz1eq",
    bg: "#10b981",
    initial: "D",
    f1_t: "Matn orqali montaj",
    f1_d: "Transkriptdagi ortiqcha so‘zni o‘chirsangiz, videoning o‘sha qismi avtomatik qirqiladi.",
    f2_t: "Studio Sound",
    f2_d: "Telefon yoki shovqinli xonadagi ovozni professional studiya mikrofoni darajasiga ko‘taradi.",
    f3_t: "To‘xtalishlarni tozalash",
    f3_d: "Nutqdagi “e-e-e”, “a-a-a” kabi to‘xtalishlar va noqulay sukunatlarni 1 bosishda yo‘qotadi.",
    benefit: "Montajchiga pul to‘lamay, Reels, YouTube yoki dars videolaringizni sifatli ovoz bilan o‘zingiz chiqarasiz.",
    prompt: "Videoni yuklang -> Studio Sound tugmasini yoqing -> 'Remove filler words' orqali nutqdagi barcha to‘xtalishlarni 1 soniyada tozalang."
  },
  apollo: {
    id: "apollo",
    name: "Apollo.io",
    kicker: "AI vosita · B2B Lead Generation",
    headline: "Xizmatingizni chet elga yoki yirik kompaniyalarga sotmoqchisiz, lekin rahbarlar kontaktini topolmayapsizmi? <b>Apollo.io</b> orqali istalgan sohadagi direktorlarning tekshirilgan email va telefonlarini topasiz.",
    category: "B2B Lead & Sotuv",
    pricing: "Freemium (Bepul limitlar bor)",
    lang: "Global platforma",
    url: "https://get.apollo.io/yy5q6cfw7xi5",
    bg: "#f59e0b",
    initial: "A",
    f1_t: "275M+ tekshirilgan kontaktlar",
    f1_d: "Soha, davlat va lavozim bo‘yicha filtrlab, rahbarlarning to‘g‘ridan-to‘g‘ri pochtasini beradi.",
    f2_t: "Avtomatik pochta zanjiri",
    f2_d: "Topilgan mijozlarga moslashtirilgan xatlar zanjirini rejalashtirib, javoblarni kuzatadi.",
    f3_t: "Xarid niyati (Buyer Intent)",
    f3_d: "Aynan hozir sizning sohangizda yechim qidirayotgan faol kompaniyalarni ko‘rsatadi.",
    benefit: "Eksport va B2B savdo bo‘limingiz uchun oylab vaqt ketadigan mijozlar bazasini bir necha soatda yig‘ib beradi.",
    prompt: "Apollo qidiruvida: Industry = Textile / Software, Location = UAE / Germany / USA, Title = Head of Procurement yoki CEO deb filtrlang."
  },
  maya: {
    id: "maya",
    name: "Tahrirchi AI",
    kicker: "AI vosita · O‘zbek tili & Matn tahriri",
    headline: "O‘zbek tilida xatosiz, ravon va professional matnlar, maqolalar va rasmiy xatlar yozmoqchimisiz? <b>Tahrirchi AI</b> kirill va lotin alifbolarida orfografik xatolarni tuzatadi va uslubiy tahrir qiladi.",
    category: "O‘zbek tili & Tahrir",
    pricing: "Freemium / Obuna",
    lang: "O‘zbek tili (Lotin & Kirill)",
    url: "https://tahrirchi.uz",
    bg: "#2563eb",
    initial: "T",
    f1_t: "Orfografiya va tinish belgilari",
    f1_d: "O‘zbek tili qoidalari bo‘yicha xatolarni aniqlab, bir bosishda to‘g‘rilaydi.",
    f2_t: "Lotin-Kirill konvertatsiyasi",
    f2_d: "Matnlarni alifbolar o‘rtasida buzilmasdan va harf xatolarisiz o‘giradi.",
    f3_t: "Uslubiy tavsiyalar",
    f3_d: "Rasmiy xatlar va maqolalar ravonligini oshirish bo‘yicha aniq takliflar beradi.",
    benefit: "O‘zbek tilida xatosiz, orfografik va stilistik jihatdan mukammal hujjatlar va maqolalar tayyorlash.",
    prompt: "Quyidagi matnni imlo, tinish belgilari va uslubiy qoidalar bo‘yicha tekshirib, xatolarini to‘g‘irla. Lotin alifbosi qoidalariga qat’iy rioya qil."
  },
  muxlisa: {
    id: "muxlisa",
    name: "UzbekVoice AI (Mohirdev)",
    kicker: "AI vosita · O‘zbekiston Nutq & Audio",
    headline: "O‘zbekcha jonli nutqni aniq matnga aylantirish (Speech-to-Text) va yozma matnni tabiiy, ohangdor o‘zbek ovozida o‘qib berish (Text-to-Speech) texnologiyasi.",
    category: "Nutq & Transkripsiya (O‘zbekiston)",
    pricing: "API & Obuna tariflari",
    lang: "O‘zbek tili (Lotin & Kirill)",
    url: "https://uzbekvoice.ai",
    bg: "#0284c7",
    initial: "Mx",
    f1_t: "O‘zbekcha nutqni aniq tanish (STT)",
    f1_d: "Turli shevalar, tez va shovqinli audio yozuvlarni yuqori aniqlikda matnga o‘giradi.",
    f2_t: "Tabiiy audio ovozlashtirish (TTS)",
    f2_d: "Kitoblar, yangiliklar va interfeyslarni jonli insonga yaqin o‘zbek ovozida o‘qiydi.",
    f3_t: "Dasturchilar uchun qulay API",
    f3_d: "Telegram botlar, mobil ilovalar va call-markazlarga bir necha qator kod bilan ulanadi.",
    benefit: "Mijozlar bilan ovozli muloqotni avtomatlashtirish va audio fayllarni oson transkripsiya qilish.",
    prompt: "Muxlisa AI API integratsiyasi: Audio faylni yuboring -> STT moduli orqali o‘zbekcha matnni qabul qilib oling."
  },
  lemlist: {
    id: "lemlist",
    name: "Lemlist",
    kicker: "AI vosita · B2B Email Outreach",
    headline: "Har bir mijoz uchun AI yordamida chuqur shaxsiylashtirilgan xatlar jo‘natish. Spamga tushmaslikni ta’minlovchi platforma.",
    category: "Email Outreach & Sotuv",
    pricing: "Sinov muddati / Obuna",
    lang: "Ko‘p tilli (Ingliz, Rus, O‘zbek)",
    url: "https://get.lemlist.com/9wfnrv5mceyj",
    bg: "#ec4899",
    initial: "L",
    f1_t: "Dinamik matn va rasm",
    f1_d: "Har bir xatga qabul qiluvchining ismi, kompaniyasi va veb-sayti skrinshotini avtomatik qo‘yadi.",
    f2_t: "Email isitish (Lemwarm)",
    f2_d: "Pochtangiz obro‘sini oshirib, spam papkasiga tushish xavfini yo‘qotadi.",
    f3_t: "Ko‘p kanalli ketma-ketlik",
    f3_d: "Email va LinkedIn aloqalarini bitta avtomatlashtirilgan zanjirga birlashtiradi.",
    benefit: "Sovuq xatlarga javob olish foizini (reply rate) 3-4 barobarga oshirish.",
    prompt: "Qabul qiluvchining veb-sayti ma'lumotlariga qarab, ularning muammosini ko'rsatuvchi 3 qatorlik kirish xati yoz."
  },
  meetgeek: {
    id: "meetgeek",
    name: "MeetGeek",
    kicker: "AI vosita · Uchrashuvlar & Bayonnomalar",
    headline: "Zoom, Google Meet va Teams uchrashuvlarini yozib olib, 1 daqiqada asosiy xulosalar va topshiriqlar bayonnomasini chiqaradi.",
    category: "Uchrashuv va Majlislar",
    pricing: "Freemium / Pro",
    lang: "O‘zbekcha, Ruscha, Inglizcha",
    url: "https://get.meetgeek.ai/uy8dxc8l9prm",
    bg: "#6366f1",
    initial: "MG",
    f1_t: "Avtomatik ulanish",
    f1_d: "Taqvimingizdagi onlayn majlisga o‘zi kirib, butun suhbatni audio va video shaklida yozib oladi.",
    f2_t: "Topshiriqlar ro‘yxati (Action Items)",
    f2_d: "Kim qaysi vazifani qachongacha bajarishi kerakligini ajratib ko‘rsatadi.",
    f3_t: "Kalit so‘zlar qidiruvi",
    f3_d: "1 soatlik majlisdan kerakli mavzuni qidiruv orqali 2 soniyada topasiz.",
    benefit: "Majlisda qo‘lda konspekt yozishdan qutulib, barcha kelishuvlarni aniq saqlash.",
    prompt: "MeetGeek xulosasi: 'Ushbu uchrashuvdagi barcha kelishuvlarni Telegram orqali jamoaga jo‘natish uchun qisqa post holatiga keltir.'"
  },
  instantly: {
    id: "instantly",
    name: "Instantly",
    kicker: "AI vosita · Mass Email Outreach",
    headline: "Katta hajmdagi B2B email kampaniyalarini xavfsiz kengaytirish, hisoblarni isitish va javoblarni AI bilan saralash.",
    category: "B2B Outreach Scale",
    pricing: "Pullik (Bepul sinov bor)",
    lang: "Global platforma",
    url: "https://refer.instantly.ai/7pwwq1hkoudw",
    bg: "#2563eb",
    initial: "IN",
    f1_t: "Cheksiz pochtalar ulash",
    f1_d: "O‘nlab domenlarni bitta markazdan boshqarish imkoniyati.",
    f2_t: "Avtomatik AI Isitish",
    f2_d: "Pochtalar reputatsiyasini doimiy yuqori saqlaydi.",
    f3_t: "AI Unibox",
    f3_d: "Mijozlarning 'qiziqdim' yoki 'kerak emas' javoblarini avtomatik ajratadi.",
    benefit: "Eksport va yirik savdo bo‘limlari uchun keng miqyosli mijozlar oqimini yo‘lga qo‘yish.",
    prompt: "Kampaniya sozlamalari: Kunlik jo‘natma soni = 35 ta / pochta, oraliq vaqt = 8 daqiqa."
  },
  mindstudio: {
    id: "mindstudio",
    name: "MindStudio",
    kicker: "AI vosita · No-Code AI Quruvchi",
    headline: "Dasturlashni bilmasdan turib kompaniyangiz uchun ichki AI ilovalar, bilimlar bazasi va mijozlar bilan muloqot agentlarini quring.",
    category: "No-Code Platforma",
    pricing: "Freemium / Pro",
    lang: "Barcha tillar",
    url: "https://get.mindstudio.ai/1eqeupsiig0i",
    bg: "#09090b",
    initial: "MS",
    f1_t: "Bir nechta modelni ulash",
    f1_d: "GPT-4o, Claude 3.5 va Llama modellarini bitta jarayonga zanjir qilib ulaydi.",
    f2_t: "Kompaniya ma'lumotlar bazasi",
    f2_d: "PDF, Word va jadvallarni yuklab, faqat o‘z ma’lumotlaringiz bo‘yicha javob beruvchi bot qurasiz.",
    f3_t: "Oson ulash (API & Embed)",
    f3_d: "Saytingizga, Telegram yoki ichki portallarga bir bosishda joylashtirish mumkin.",
    benefit: "Dasturchi yollamasdan, biznes jarayonlaringiz uchun shaxsiy AI yordamchilar qurish.",
    prompt: "MindStudio Workflow: Input -> Knowledge Base Search -> Claude 3.5 Sonnet Reasoning -> Format Output."
  },
  billz: {
    id: "billz",
    name: "Billz AI",
    kicker: "AI vosita · O‘zbekiston Riteyl",
    headline: "O‘zbekiston va mintaqa chakana savdo tarmoqlari uchun intellektual tahlil va kassa integratsiyasi.",
    category: "Riteyl & Savdo Tahlili",
    pricing: "Korporativ tariflar",
    lang: "O‘zbek tili, Rus tili",
    url: "https://billz.io",
    bg: "#4f46e5",
    initial: "B",
    f1_t: "Talabni bashoratlash",
    f1_d: "Qaysi tovar qaysi faslda va qaysi filialda ko‘p sotilishini oldindan aytadi.",
    f2_t: "Inventar xavfsizligi",
    f2_d: "Tovarlar yetishmovchiligi yoki omborda uzoq yotib qolishini oldini oladi.",
    f3_t: "Mijozlar sodiqligi",
    f3_d: "Doimiy xaridorlar xatti-harakatini tahlil qilib, shaxsiy chegirmalar shakllantiradi.",
    benefit: "Do‘kon daromadini oshirish va ortiqcha ombor xarajatlarini 25% ga qisqartirish.",
    prompt: "Oxirgi 90 kunlik cheklar tahlili asosida ABC-tahlil hisobotini ko‘rsat."
  },
  tilmoch: {
    id: "tilmoch",
    name: "Tilmoch AI",
    kicker: "AI vosita · Tarjima & Turkiy Tillar",
    headline: "Turkiy tillar oilasi va o‘zbek tili uchun ixtisoslashgan, nozik ma’no va iboralarni aniq tarjima qiluvchi hamda nutqni tanuvchi sun’iy intellekt platformasi.",
    category: "Tarjima & Turkiy Tillar",
    pricing: "Freemium / API",
    lang: "O‘zbek tili, Qozoq, Turk, Ingliz",
    url: "https://tilmoch.ai",
    bg: "#0284c7",
    initial: "Tl",
    f1_t: "Kontekstual tarjima",
    f1_d: "So‘zma-so‘z emas, o‘zbek tilining jonli frazeologizmi va mantiqiy ma’nosini saqlagan holda tarjima qiladi.",
    f2_t: "Turkiy tillar ko‘prigi",
    f2_d: "Qozoq, qirg‘iz, turk va qoraqalpoq tillari o‘rtasida to‘g‘ridan-to‘g‘ri vositachisiz tarjima.",
    f3_t: "API va integratsiya",
    f3_d: "Kompaniyalar va ilovalar o‘z tizimlariga tezkor ulashi uchun dasturiy interfeys (API).",
    benefit: "Murakkab xorijiy hujjatlar va texnik matnlarni o‘zbek tiliga tabiiy va ravon o‘girish.",
    prompt: "Ushbu texnik xalqaro shartnomani o‘zbek tiliga professional yuridik atamalar me’yorida tarjima qilib ber."
  },
  aisha: {
    id: "aisha",
    name: "Aisha AI",
    kicker: "AI vosita · Ovozli AI & Call-markaz",
    headline: "O‘zbekiston kompaniyalari, banklar va call-markazlar uchun kechayu-kunduz mijozlar qo‘ng‘iroqlariga javob beruvchi va so‘rovlarni qabul qiluvchi aqlli ovozli agentlar.",
    category: "Ovozli AI & Call-markaz",
    pricing: "B2B Korporativ",
    lang: "O‘zbek tili, Rus tili",
    url: "https://aisha.group",
    bg: "#0d9488",
    initial: "Ai",
    f1_t: "Ovozli agentlar (Voice AI)",
    f1_d: "Mijozlarning telefon orqali bergan savollariga tabiiy ovozda, kutishlarsiz zudlik bilan javob qaytaradi.",
    f2_t: "Ko‘p tilli muloqot",
    f2_d: "O‘zbek va rus tillarida ravon suhbatlashib, mijoz qaysi tilda gapirsa, shu tilda javob beradi.",
    f3_t: "CRM bilan integratsiya",
    f3_d: "Qo‘ng‘iroq davomida olingan ma’lumotlarni kompaniya ichki tizimiga darhol ro‘yxatga oladi.",
    benefit: "Call-markaz xarajatlarini 60% gacha kamaytirish va tungi vaqtlarda ham mijozlarni yo‘qotmaslik.",
    prompt: "Kompaniyamizga tushadigan standart buyurtma holatini tekshirish qo‘ng‘iroqlari uchun 2 daqiqalik ovozli muloqot ssenariysini tuzib ber."
  },
  lindy: {
    id: "lindy",
    name: "Lindy",
    kicker: "AI vosita · Avtonom AI Assistent",
    headline: "Kundalik takroriy ishlarni bajarishdan charchadingizmi? <b>Lindy</b> xatlarga javob beradigan, uchrashuvlarni belgilaydigan va shaxsiy topshiriqlarni avtonom bajaruvchi AI yordamchingizdir.",
    category: "AI Assistent & Unumdorlik",
    pricing: "Freemium / Obuna",
    lang: "Ingliz, Rus, Ko‘p tilli",
    url: "https://try.lindy.ai/9jnuq63xr11e",
    bg: "#ea580c",
    initial: "L",
    f1_t: "Avtonom topshiriqlar",
    f1_d: "Pochtani kuzatadi, xatlarni saralaydi va oldindan berilgan qoidalar bo‘yicha avtomatik javob tayyorlaydi.",
    f2_t: "Taqvim va uchrashuvlar",
    f2_d: "Mijozlar bilan mos vaqtni o‘zi kelishib, Google Calendar yoki Outlook’ka kiritadi.",
    f3_t: "3000+ dasturga ulanish",
    f3_d: "Slack, WhatsApp, Gmail va CRM tizimlaringiz bilan to‘g‘ridan-to‘g‘ri sinxronlashadi.",
    benefit: "Rutina ishlarga sarflanadigan kunlik 2-3 soat vaqtingizni asosiy strategik vazifalarga bo‘shatadi.",
    prompt: "Menga kelgan yangi hamkorlik xatlarini tekshir, ularning kompaniyasi haqida qisqa ma'lumot tayyorla va menga Telegram orqali xulosa ber."
  },
  adcreative: {
    id: "adcreative",
    name: "AdCreative.ai",
    kicker: "AI vosita · Reklama va Kreativ",
    headline: "Targeting va reklama uchun har safar yangi banner yasashga vaqt ketayotgan bo‘lsa, <b>AdCreative.ai</b> sun’iy intellekt orqali konversiyasi yuqori bannerlar va matnlarni daqiqalarda ishlab chiqadi.",
    category: "Reklama & Marketing",
    pricing: "Bepul sinov / Obuna",
    lang: "Global marketing",
    url: "https://free-trial.adcreative.ai/jb870cr6hwhe",
    bg: "#e11d48",
    initial: "AC",
    f1_t: "Konversiyaga moslangan bannerlar",
    f1_d: "Millionlab muvaffaqiyatli reklamalar tahlili asosida xaridorlarni jalb qiluvchi dizaynlar shakllantiradi.",
    f2_t: "Barcha formatlar bir bosishda",
    f2_d: "Instagram Story, Post, Facebook Feed va Display bannerlarini 1 soniyada moslashtiradi.",
    f3_t: "AI matn generatori",
    f3_d: "Reklama uchun diqqatni tortuvchi sarlavha va Call-to-Action (CTA) matnlarini yozib beradi.",
    benefit: "Grafik dizayner kutmasdan, reklama kampaniyalarini bir necha barobar tezroq ishga tushirish imkoni.",
    prompt: "Mahsulotimiz: B2B konsalting xizmatlari. Ranglar: quyuq ko‘k va zumrad. Instagram Stories formati uchun 3 ta kuchli taklif banneri tayyorla."
  },
  beautifulai: {
    id: "beautifulai",
    name: "Beautiful.ai",
    kicker: "AI vosita · Taqdimot Dizayni",
    headline: "Taqdimot tayyorlashda slaydlardagi shakllar va matnlarni to‘g‘rilashga soatlab vaqt ketadimi? <b>Beautiful.ai</b> sun’iy intellekt yordamida dizayn qoidalariga avtomatik rioya qilib, professional slaydlar tuzadi.",
    category: "Taqdimot & Dizayn",
    pricing: "Sinov muddati / Pro",
    lang: "Global platforma",
    url: "https://beautifulai.partnerlinks.io/rvvr8zuu35ig",
    bg: "#0ea5e9",
    initial: "B",
    f1_t: "Aqlli slayd shablonlari",
    f1_d: "Matn yoki rasm qo‘shganingizda slayd dizayni o‘zini-o‘zi mukammal proporsiyada moslashtiradi.",
    f2_t: "Brend qoidalari (Brand Kit)",
    f2_d: "Kompaniyangiz logotipi, shriftlari va korporativ ranglarini barcha slaydlarga birdek tatbiq etadi.",
    f3_t: "Jamoaviy ishlash",
    f3_d: "Butun jamoa bilan birgalikda taqdimot ustida real vaqt rejimida ishlash imkoniyati.",
    benefit: "Har qanday investor yoki mijoz oldida taassurot qoldiruvchi, xalqaro darajadagi taqdimotlar qurish.",
    prompt: "Kompaniyamizning yillik moliyaviy hisoboti va kelasi yil maqsadlari uchun 10 slayddan iborat korporativ taqdimot dizaynini tuz."
  },
  calilio: {
    id: "calilio",
    name: "Calilio",
    kicker: "AI vosita · Bulutli Telefoniya",
    headline: "Xalqaro mijozlar bilan muloqot va qo‘ng‘iroqlarni boshqarish uchun <b>Calilio</b> AI asosidagi virtual telefoniya, suhbatlar tahlili va ko‘p kanalli aloqani taqdim etadi.",
    category: "Telefoniya & Mijozlar aloqasi",
    pricing: "Sinov muddati / Oylik tariflar",
    lang: "Ko‘p tilli (Global VoIP)",
    url: "https://try.calilio.com/yvlkop2jok4w",
    bg: "#6d28d9",
    initial: "C",
    f1_t: "Xalqaro virtual raqamlar",
    f1_d: "AQSH, Yevropa va 100 dan ortiq mamlakatlarning mahalliy raqamlarini bir necha daqiqada faollashtirish.",
    f2_t: "AI qo‘ng‘iroqlar transkripsiyasi",
    f2_d: "Menejerlarning mijozlar bilan audio suhbatlarini matnga aylantirib, asosiy kelishuvlarni ajratadi.",
    f3_t: "Mijozlar kayfiyati tahlili (Sentiment)",
    f3_d: "Mijozning suhbat davomidagi mamnunlik darajasi va e’tirozlarini avtomatik baholaydi.",
    benefit: "Xorijiy mijozlarga ishonchli xalqaro raqamlar orqali xizmat ko‘rsatish va savdo sifatini nazorat qilish.",
    prompt: "Xorijiy mijozlar bilan bo‘lgan 15 daqiqalik qo‘ng‘iroq yozuvini tahlil qil, mijozning e’tirozlari va keyingi qadamlarni aniqlab ber."
  },
  chatgpt: {
    id: "chatgpt",
    name: "ChatGPT (OpenAI)",
    kicker: "AI vosita · Universal LLM & Agentlar",
    headline: "Dunyoning eng ommabop universal sun'iy intellekt assistenti. Murakkab vazifalarni tahlil qilish, matnlar va kod yozish hamda Advanced Voice orqali jonli muloqot qilish tizimi.",
    category: "Universal AI & Matn",
    pricing: "Freemium / Plus ($20/oy)",
    lang: "O‘zbek, Rus, Ingliz (Mukammal)",
    url: "https://chatgpt.com",
    bg: "#10a37f",
    initial: "GPT",
    f1_t: "GPT-4o va Jonli Ovozli Suhbat",
    f1_d: "Haqiqiy insondek kechikishsiz ovozda suhbatlashish va real vaqtda maslahat olish.",
    f2_t: "Custom GPTs & Agentlar",
    f2_d: "O'z biznesingiz yoki shaxsiy ehtiyojingiz uchun kodsiz ixtisoslashgan AI yordamchilarni sozlash.",
    f3_t: "Fayllar, PDF va Excel Tahlili",
    f3_d: "Katta jadvallar, shartnomalar va tasvirlarni bir zumda o'qib, xulosalar chiqarish.",
    benefit: "Kundalik korporativ muloqot, hujjat tayyorlash va tahlil ishlarini 3-5 baravarga tezlashtirish.",
    prompt: "Siz B2B strategik maslahatchisiz. Kompaniyamizning savdo konveyerini tahlil qiling va konversiyani oshirish bo'yicha 5 ta aniq amaliy qadamni ko'rsatib bering."
  },
  claude: {
    id: "claude",
    name: "Claude (Anthropic)",
    kicker: "AI vosita · Chuqur Mantiq, Tahlil & Kodlash",
    headline: "Anthropic tomonidan ishlab chiqilgan eng ilg'or intellektual model (Claude 3.5 Sonnet). Katta hajmdagi hujjatlarni chuqur tahlil qilish va dasturchilar darajasida kod yozishda dunyo yetakchisi.",
    category: "Tahlil & Dasturlash",
    pricing: "Freemium / Pro ($20/oy)",
    lang: "O‘zbek, Rus, Ingliz (Mukammal adabiy til)",
    url: "https://claude.ai",
    bg: "#d97706",
    initial: "C",
    f1_t: "Artifacts Interaktiv Muhiti",
    f1_d: "Kod, veb-interfeys va grafik chizmalarni real vaqtda alohida oynada darhol ko'rish va tahrirlash.",
    f2_t: "200,000 Tokenli Katta Xotira",
    f2_d: "Yuzlab sahifalik shartnomalar, kitoblar va butun kod bazasini bitta so'rovda tahlil qilish.",
    f3_t: "Eng Yuqori Mantiqiy Aniqlik",
    f3_d: "Faktlarga tayangan aniq javoblar, minimal xatolik va chuqur adabiy tahrir qobiliyati.",
    benefit: "Murakkab tahliliy hisobotlar, yuridik hujjatlar va dasturiy ta'minot yozishda eng ishonchli vosita.",
    prompt: "Ushbu 20 sahifalik xizmat ko'rsatish shartnomasini audit qiling. Biznesimiz uchun yashirin moliyaviy va yuridik xatarlarni aniqlab, ularni bartaraf etuvchi himoya bandlarini tavsiya eting."
  },
  gemini: {
    id: "gemini",
    name: "Google Gemini",
    kicker: "AI vosita · Multimodal & Katta Xotira",
    headline: "Google'ning 1-2 million tokenli ulkan xotiraga ega eng yangi sun'iy intellekti. Soatlab davom etgan video, audio va Google Workspace (Docs, Gmail, Drive) bilan to'liq integratsiya.",
    category: "Multimodal & Tadqiqot",
    pricing: "Freemium / Advanced ($20/oy)",
    lang: "O‘zbek, Rus, Ingliz (To‘liq qo‘llab-quvvatlanadi)",
    url: "https://gemini.google.com",
    bg: "#2563eb",
    initial: "G",
    f1_t: "1M-2M Tokenli Ulkan Xotira",
    f1_d: "1 soatlik to'liq videoni yoki butun bir yillik hisobotlarni bittada xotirasida saqlab tahlil qiladi.",
    f2_t: "Google Ekotizimi Integratsiyasi",
    f2_d: "Google Docs, Gmail va Google Drive hujjatlaringiz bilan to'g'ridan-to'g'ri bog'lanib ishlaydi.",
    f3_t: "Real-Time Google Qidiruvi",
    f3_d: "Internetdagi eng yangi yangilik va voqealarga Google qidiruvi orqali tayanadi.",
    benefit: "Katta hajmdagi media, audio va video fayllarni tezda tahlil qilishda eng qulay yordamchi.",
    prompt: "Ushbu video yozuvdagi barcha asosiy mavzularni vaqt belgilari (timestamps) bilan ajratib, har bir mavzu bo'yicha 2 qatorlik xulosa tayyorlab ber."
  },
  ezgusavdo: {
    id: "ezgusavdo",
    name: "EzguSavdo AI",
    kicker: "AI vosita · O‘zbekiston Tovar & Savdo Boti",
    headline: "Chakana savdo va tovar bizneslari uchun 24/7 ishlovchi AI-sotuvchi. Instagram Direct, Telegram va veb-saytda mijozlarga tovar topadi, Billz va 1C qoldiqlarini tekshiradi hamda nazoratli savdolashadi.",
    category: "AI Sotuvchi & E-commerce (O‘zbekiston)",
    pricing: "Freemium (50 ta bepul dialog / pullik tariflar)",
    lang: "O‘zbek tili, Rus tili",
    url: "https://ezgusavdo.uz/uz",
    bg: "#07162f",
    initial: "ES",
    f1_t: "Billz va 1C qoldiqlari sinxronizatsiyasi",
    f1_d: "Haqiqiy narx va ombor qoldiqlari bo‘yicha aniq ma'lumot beradi, quruq taxmin qilmaydi.",
    f2_t: "Nazoratli savdolashuv (Marja himoyasi)",
    f2_d: "Mijoz chegirma so‘raganda, biznes belgilagan minimal narxdan pastga tushmasdan chegirma hisoblaydi.",
    f3_t: "Ovozli xabarlarni tushunish",
    f3_d: "O‘zbek va rus tillaridagi audio/ovozli so‘rovlarni tushunib, mos tovarlarni tavsiya qiladi.",
    benefit: "Kunlik o‘nlab javobsiz xabarlarni nolgacha tushirib, sotuv bo‘limi yuklamasini kamaytirish.",
    prompt: "EzguSavdo ssenariysi: Xaridor mahsulot so‘raganda, ombor qoldig‘ini tekshirib, yetkazib berish shartlari bilan darhol rasmiylashtirish."
  },
  ailo: {
    id: "ailo",
    name: "AILO",
    kicker: "AI vosita · Instagram & Telegram AI Sotuvchi",
    headline: "Instagram Reels izohlari va Direct xabarlarini 24/7 savdoga aylantiruvchi, 8 soniyada insondek samimiy muloqot qiluvchi va buyurtmalarni CRM'ga uzatuvchi aqlli milliy AI-sotuvchi tizimi.",
    category: "AI Sotuvchi & Direct Voronka (O‘zbekiston)",
    pricing: "Jonli Demo & Audit asosida",
    lang: "O‘zbek tili, Rus tili",
    url: "https://ailo.gptify.uz",
    bg: "#ff5e4d",
    initial: "Ai",
    f1_t: "8 soniyada Reels-to-Direct voronkasi",
    f1_d: "Reels izohlariga darhol javob berib, bir vaqtning o‘zida shaxsiy Direct ochadi va xaridorni qizdiradi.",
    f2_t: "Erkin so‘zlashuv & E’tirozlarni yopish",
    f2_d: "Mijozning 'qimmat-ku' yoki boshqa e’tirozlarini o‘zbek tilida erkin tushunib, samimiy muloqot bilan yechadi.",
    f3_t: "amoCRM, Bitrix24 & Telegram integratsiyasi",
    f3_d: "Xaridga tayyor lidlar va buyurtma ma'lumotlarini savdo bo‘limi CRM bazasiga avtomatik kiritadi.",
    benefit: "Kecha-yu kunduz har bir murojaatga 8 soniyada javob berib, savdo konversiyasini oshirish va operatorlar yuklamasini kamaytirish.",
    prompt: ""
  },
  ildam: {
    id: "ildam",
    name: "ILDAM",
    kicker: "AI vosita · B2B & YaTT AI Savdo CRM",
    headline: "Telegram va Instagramdan keluvchi har bir lidga 10 soniyada javob beruvchi 24/7 AI sotuvchi, zamonaviy savdo konveyeri va 1,200+ mahalliy korxona tasdiqlangan ochiq B2B bazasiga ega aqlli CRM tizimi.",
    category: "B2B Savdo & CRM (O‘zbekiston)",
    pricing: "Oyiga $99 dan boshlab",
    lang: "O‘zbek tili, Rus tili",
    url: "https://ildam.gptify.uz",
    bg: "#f59e0b",
    initial: "Il",
    f1_t: "10 soniyada tezkor javob (24/7)",
    f1_d: "Telegram va Instagram Direct orqali kelgan yangi mijozlarga 10 soniyada mahsulot, narx va xizmatlarni tushuntiradi hamda savdoni yopadi.",
    f2_t: "1,200+ Korxona B2B Bazasi",
    f2_d: "O‘zbekistondagi korxona va tashkilotlarning tasdiqlangan ochiq rekvizitlari va har biriga moslashtirilgan outreach skriptlari.",
    f3_t: "5 bosqichli CRM konveyer va AI Copilot",
    f3_d: "Lidni saralashdan to bitim yopilishigacha bo‘lgan CRM jarayonlarini boshqaradi, tijorat taklifnomalari va e’tirozlarni yechadi.",
    benefit: "Kechki va dam olish kunlaridagi mijoz yo‘qotishlarini nolgacha tushirib, B2B savdo aylanmasini oshirish.",
    prompt: ""
  },
  meet: {
    id: "meet",
    name: "GPTify Meet",
    kicker: "AI vosita · Uchrashuv Bayonnomasi & Ovoz Tahlili",
    headline: "Zoom, Google Meet, Teams yoki oflayn uchrashuvlarni botlarsiz yozib oling. GPTify Meet o‘zbekcha transkripsiya, qarorlar va topshiriqlarni kompyuteringizning o‘zida tayyorlaydi.",
    category: "Uchrashuv & Ovoz Tahlili (O‘zbekiston)",
    pricing: "Bepul demo va konsultatsiya asosida",
    lang: "O‘zbek tili, Rus tili, Ingliz tili",
    url: "https://meet.gptify.uz",
    bg: "#5b4bf2",
    initial: "Mt",
    f1_t: "Botlarsiz maxfiy yozib olish (Zero-Bot)",
    f1_d: "Uchrashuvga begona bot kirmaydi va qatnashuvchilarni bezovta qilmaydi. Kompyuteringiz audio oqimini to‘g‘ridan-to‘g‘ri yozadi.",
    f2_t: "O‘zbek tili va erkin nutq transkripsiyasi",
    f2_d: "Groq Whisper va moslashtirilgan sun’iy intellekt modeli jamoaviy muhokamalarni yuqori aniqlikda matnga aylantiradi.",
    f3_t: "Strukturaviy qarorlar va topshiriqlar taqsimoti",
    f3_d: "Uchrashuv tugashi bilanoq qabul qilingan qarorlar, mas’ullar, muddatlar va potensial xavflar avtomatik shakllanadi.",
    benefit: "Uchrashuvdan so‘ng bayonnoma yozishga ketadigan 30-40 daqiqa vaqtni tejash va kelishuvlarni yo‘qotmaslik.",
    prompt: ""
  },
  deepseek: {
    id: "deepseek",
    name: "DeepSeek",
    kicker: "AI vosita · Ochiq Kodli LLM & Mantiqiy Fikrlash",
    headline: "Dunyo bozorini larzaga keltirgan yuqori unumli ochiq kodli modellar (V3 va R1). Murakkab matematika, dasturlash va tahliliy xulosalarni eng arzon narxda yoki bepul taqdim etuvchi kuchli sun’iy intellekt.",
    category: "LLM & Mantiqiy Fikrlash",
    pricing: "Bepul / Hamyonbop API",
    lang: "O‘zbek, Rus, Ingliz, Xitoy (Ko‘p tilli)",
    url: "https://www.deepseek.com",
    bg: "#1d4ed8",
    initial: "DS",
    f1_t: "DeepSeek-R1 Fikrlash Modeli",
    f1_d: "OpenAI o1 darajasidagi chuqur mantiqiy fikrlash, matematik masalalar va mantiqiy zanjirlarni bosqichma-bosqich yechadi.",
    f2_t: "Ochiq Kod va Arzon Narx",
    f2_d: "Xususiy serverlar yoki bulutli tizimlarga boshqa modellardan bir necha barobar arzon narxda integratsiya qilish imkoni.",
    f3_t: "Dasturlash va Algoritmlar",
    f3_d: "Murakkab dasturiy kod yozish, algoritmlarni tekshirish va texnik hisobotlarni tuzishda yetakchi daraja.",
    benefit: "Minimal byudjet bilan jahonning eng kuchli mantiqiy sun’iy intellekt imkoniyatlaridan to‘liq foydalanish.",
    prompt: "Kompaniyamizning ma'lumotlar bazasi so'rovlarini optimallashtirish va tizim tezligini oshirish bo'yicha bosqichma-bosqich texnik yechim taklif qiling."
  },
  grok: {
    id: "grok",
    name: "Grok (xAI)",
    kicker: "AI vosita · Haqiqiy Vaqt Tahlili & Erkin Mantiq",
    headline: "Ilon Mask (xAI) tomonidan ishlab chiqilgan, X (Twitter) platformasidagi ma'lumotlar oqimini real vaqtda tahlil qiluvchi, erkin muloqot va kuchli dasturlash benchmarklariga ega intellektual tizim.",
    category: "LLM & Real-Time Qidiruv",
    pricing: "X Premium / Grok Pro",
    lang: "O‘zbek, Rus, Ingliz (To‘liq qo‘llab-quvvatlanadi)",
    url: "https://x.ai",
    bg: "#0f172a",
    initial: "Gr",
    f1_t: "Real-Vaqt X (Twitter) Tahlili",
    f1_d: "Dunyoda yuz berayotgan eng so'nggi yangiliklar, voqealar va texnologik xabarlarni soniyalar ichida umumlashtiradi.",
    f2_t: "Grok Reasoning & Kodlash",
    f2_d: "Murakkab matematika, fan va dasturlash masalalarida jahonning yetakchi modellari bilan raqobatlasha oladigan mantiq.",
    f3_t: "Aurora Multimodal Tahlil",
    f3_d: "Tasvirlar, infografikalar va diagrammalarni chuqur tushunib, vizual savollarga aniq javob beradi.",
    benefit: "Global yangiliklar va bozor tendensiyalarini internetda paydo bo‘lishi bilanoq real vaqtda tahlil qilish.",
    prompt: "Global AI va texnologiya bozorida so'nggi 24 soat ichida sodir bo'lgan eng muhim 3 ta voqeani qisqa tahlil qilib bering."
  },
  higgsfield: {
    id: "higgsfield",
    name: "Higgsfield AI",
    kicker: "AI vosita · Kinematik Video & Harakat Generatsiyasi",
    headline: "Kino darajasidagi video generatsiya platformasi. Bitta rasm yoki matnli ko‘rsatmadan kinematik kamera harakatlari, inson mimikasi va professional rakurslarga ega yuqori sifatli videolarni ishlab chiqadi.",
    category: "Video & Kinematik Harakat",
    pricing: "Freemium / Pro tariflar",
    lang: "Global platforma",
    url: "https://higgsfield.ai",
    bg: "#7c2d12",
    initial: "HF",
    f1_t: "Kinematik Kamera Nazorati",
    f1_d: "Kameraning aylanishi, yaqinlashishi, panorama va dron harakatlarini rejissyor kabi erkin boshqarish.",
    f2_t: "Inson Qiyofasi va Harakat Aniq Saqlanishi",
    f2_d: "Qahramon yuzi, mimikasi va tana harakatlari deformatsiyasiz, realistik dinamikada harakatlanadi.",
    f3_t: "SMM va Reklama Roliklari",
    f3_d: "Instagram Reels, TikTok va tijorat videolari uchun qimmatbaho videosyomkalarsiz jozibador kontent tayyorlash.",
    benefit: "Katta byudjetli videostudiya yollamasdan, yuqori sifatli video roliklar va kreativlarni tezda ishlab chiqish.",
    prompt: "Kamera sekin aylanib yaqinlashadi, qahramon tabassum bilan shahar manzarasiga qaraydi, kinematik yumshoq yorug'lik."
  },
  perplexity: {
    id: "perplexity",
    name: "Perplexity AI",
    kicker: "AI vosita · Manbali AI Qidiruv & Tadqiqot",
    headline: "An’anaviy qidiruv tizimlariga eng zamonaviy muqobil. Internetdagi ma’lumotlarni o‘rganib, har bir ma’lumotiga aniq manba havolasini ilova qilgan holda faktlarga asoslangan konspekt tayyorlaydi.",
    category: "AI Qidiruv & Tadqiqot",
    pricing: "Freemium / Pro ($20/oy)",
    lang: "O‘zbek, Rus, Ingliz",
    url: "https://www.perplexity.ai",
    bg: "#134e4a",
    initial: "P",
    f1_t: "Manbalarga Asoslangan Javoblar",
    f1_d: "Har bir ma'lumotning asl manbasini havolalar bilan ko'rsatadi, taxminiy noto'g'ri faktlardan xoli.",
    f2_t: "Pro Search Chuqur Qidiruv",
    f2_d: "Murakkab tadqiqotlar uchun internetdagi o'nlab tahliliy maqolalarni ketma-ket solishtirib chiqadi.",
    f3_t: "Hujjatlar va Hisobotlar Tahlili",
    f3_d: "Katta PDF va moliyaviy hisobotlarni yuklab, ulardagi statistik ko'rsatkichlarni tezkor qidirish.",
    benefit: "Keraksiz reklamali saytlarni kezmasdan, kerakli tahliliy ma'lumotni soniyalarda ishonchli manbasi bilan olish.",
    prompt: "2026-yil holatiga ko'ra Markaziy Osiyoda elektron tijorat va fintech sohasidagi asosiy raqamlar va manbalarni keltiring."
  },
  cursor: {
    id: "cursor",
    name: "Cursor AI",
    kicker: "AI vosita · Dasturchilar Uchun AI Muharrir",
    headline: "Dasturchilar orasida eng ommabop sun’iy intellekt muharriri (VS Code asosida). Butun kod bazangizni chuqur tushunib, dasturiy kod yozish, xatolarni tuzatish va arxitekturani tezlashtiradi.",
    category: "Dasturlash & Kod Agentlari",
    pricing: "Freemium / Pro ($20/oy)",
    lang: "Global (Barcha dasturlash tillari)",
    url: "https://www.cursor.com",
    bg: "#18181b",
    initial: "Cur",
    f1_t: "Butun Loyiha Konteksti (@Codebase)",
    f1_d: "Alohida fayllar bilan emas, butun repozitoriy va bog'lanishlarni tushungan holda ishlaydi.",
    f2_t: "Aqlli Tab Avtotoliqlash",
    f2_d: "Dasturchining keyingi fikrini oldindan sezib, bir nechta qator kodni bir zumda taklif qiladi.",
    f3_t: "Claude 3.5 Sonnet va GPT-4o Tanlash",
    f3_d: "Ilg'or modellar yordamida murakkab refaktoring, testlar yozish va xatolarni tezda tuzatish.",
    benefit: "Dasturchilarning kunlik mahsuldorligini 2-3 barobarga oshirish va yangi funksiyalarni tezroq ishga tushirish.",
    prompt: "Ushbu API metodga ma'lumotlar xavfsizligi, validatsiya va xatolarni qayd qilish mexanizmini qo'shing."
  },
  midjourney: {
    id: "midjourney",
    name: "Midjourney",
    kicker: "AI vosita · Professional Tasvir & Vizual Generatsiya",
    headline: "Fotorealistik va badiiy san’at darajasidagi vizual tasvirlarni ishlab chiqaruvchi dunyoning eng yetakchi sun’iy intellekt platformasi. Dizayn, marketing va brending uchun cheksiz tasavvur imkoniyatlari.",
    category: "Tasvir & Vizual Dizayn",
    pricing: "Oylik obuna ($10/oy dan)",
    lang: "Global (Inglizcha promptlar)",
    url: "https://www.midjourney.com",
    bg: "#312e81",
    initial: "MJ",
    f1_t: "Fotorealizm va Kinematik Sifat",
    f1_d: "Haqiqiy fotosuratdan ajratib bo'lmaydigan darajada nozik yorug'lik, to'qima va detallarga ega tasvirlar.",
    f2_t: "Uslub va Brending Moslashuvchanligi",
    f2_d: "3D render, arxitektura, illyustratsiya va mahsulot dizayni kabi yuzlab uslublarda vizuallar tayyorlash.",
    f3_t: "Veb-interfeys va Tezkor Boshqaruv",
    f3_d: "Yangi veb-platforma orqali rasmlarni tahrirlash, o'lchamini kengaytirish va yangi elementlar qo'shish.",
    benefit: "Grafik dizayn va reklama konseptlarini ishlab chiqish xarajatlarini sezilarli qisqartirish.",
    prompt: "Zamonaviy Toshkent arxitekturasi uslubidagi ekologik osmono'par bino, quyosh botishi, fotorealistik 8K."
  },
  cubeo: {
    id: "cubeo",
    name: "Cubeo AI",
    kicker: "AI vosita · Avtonom AI Agentlar & No-Code Jamoa",
    headline: "Biznes jarayonlari va mijozlar bilan muloqotni avtomatlashtiruvchi, bir necha daqiqada kodsiz shaxsiy avtonom AI agentlar jamoasini qurish platformasi.",
    category: "AI Agentlar & Avtomatlashtirish",
    pricing: "Bepul sinov / Obuna",
    lang: "O‘zbek tili, Rus tili, Ingliz tili",
    url: "https://cubeo.ai",
    bg: "#3c409a",
    initial: "C",
    f1_t: "Kodsiz AI agentlar qurish (No-Code)",
    f1_d: "Dasturlash bilimlarisiz o‘z biznesingiz bilimlar bazasi va CRM tizimiga ulangan ixtisoslashgan agentlarni sozlang.",
    f2_t: "Tayyor AI agentlar kutubxonasi",
    f2_d: "Mijozlarni qo‘llab-quvvatlash, lido-generatsiya va tahlil uchun darhol ishga tushirish mumkin bo‘lgan tayyor agentlar.",
    f3_t: "Ko‘p kanalli integratsiya (Omnichannel)",
    f3_d: "Veb-sayt vidjeti, Telegram, WhatsApp va ichki korporativ tizimlarga uzluksiz ulanish imkoniyati.",
    benefit: "Biznesdagi takroriy vazifalarni 24/7 avtonom ishlovchi AI agentlar jamoasiga yuklab, inson resursini strategik ishlarga yo‘naltirish.",
    prompt: "Korxonamiz mijozlariga xizmat ko'rsatish bo'yicha e'tirozlarni yechuvchi va eng ko'p beriladigan savollarga professional javob beruvchi AI agent profilini sozlash."
  }
};
